export {
  PermissionBundleSchema,
  PermissionDefinitionSchema,
  ProductAccessDeclarationSchema,
  SystemGroupDefinitionSchema,
} from '../contracts/access';
export {
  ArtifactManifestSchema,
  OutputRecordSchema,
  StorageLocatorSchema,
} from '../contracts/artifact';
export {
  CapabilityRegistryDocumentSchema,
  CapabilityRegistryEntrySchema,
  CapabilityRegistrySourceSchema,
  CapabilitySourceTypeSchema,
  CapabilityManifestSchema,
  ContractPortSchema,
} from '../contracts/capability';
export {
  ContractMetadataSchema,
  EntityRefSchema,
  JsonObjectSchema,
  JsonValueSchema,
} from '../contracts/common';
export {
  AgentConfigurationCapabilitySchema,
  StudioAgentModeSchema,
  AgentModeSchema,
  AgentModeCapabilitiesSchema,
  AgentResourceModeSupportSchema,
  AgentSessionCapabilitiesSchema,
  AgentSessionCapabilitySchema,
  AgentSessionPermissionProfileSchema,
  AgentSessionActiveBranchSchema,
  AgentSessionCommandPolicySchema,
  AgentSessionCommandErrorCodeSchema,
  AgentSessionCommandResultSchema,
  AgentSessionCommandSchema,
  AgentSessionContinuationRequestSchema,
  AgentSessionContinuationResultSchema,
  AgentSessionCommandTypeSchema,
  AgentSessionEventSchema,
  AgentSessionContextInheritanceSchema,
  AgentSessionLineageSchema,
  AgentSessionRunEventSchema,
  AgentSessionSnapshotSchema,
  AgentSessionStatusSchema,
  AgentSessionTerminalStatusSchema,
  AgentSessionRunSchema,
  AgentSessionTargetedCommandSchema,
  AgentSessionViewModelSchema,
  AgentWorkbenchAgentItemSchema,
  AgentWorkbenchComposerAttachmentSchema,
  AgentWorkbenchComposerCapabilitiesSchema,
  AgentWorkbenchComposerModelOptionSchema,
  AgentWorkbenchComposerQueueItemSchema,
  AgentWorkbenchComposerStatusSchema,
  AgentWorkbenchComposerViewModelSchema,
  AgentWorkbenchQuickStartCategorySchema,
  AgentWorkbenchQuickStartIconSchema,
  AgentWorkbenchQuickStartSectionSchema,
  AgentWorkbenchQuickStartTemplateActionSchema,
  AgentWorkbenchQuickStartTemplateSchema,
  AgentWorkbenchQuickStartViewModelSchema,
  AgentWorkbenchCollectionStatusSchema,
  AgentWorkbenchNavigationCapabilitiesSchema,
  AgentWorkbenchNavigationItemStatusSchema,
  AgentWorkbenchNavigationViewModelSchema,
  AgentWorkbenchSessionItemSchema,
  AgentExecutionModeSchema,
} from '../contracts/agent';
export {
  AgentRuntimeEventSchema,
  CompletionEventSchema,
  CompletionHeaderSchema,
  ExecutionLinkSchema,
  RequestScopeSchema,
} from '../contracts/context';
export {
  ApplicationRunSchema,
  BodyRelationRecordSchema,
  DataContinuityEnvelopeSchema,
  ExpiringAccessGrantSchema,
} from '../contracts/continuity';
export {
  DomainEventSchema,
  LineageRecordSchema,
  OntologyDefinitionSchema,
  ProjectionSpecSchema,
  SourceRecordRefSchema,
} from '../contracts/data';
export {
  CompiledMenuActionBehaviorSchema,
  CompiledMenuBehaviorSchema,
  CompiledMenuDividerNodeSchema,
  CompiledMenuGroupNodeSchema,
  CompiledMenuItemAccessSchema,
  CompiledMenuItemNodeSchema,
  CompiledMenuNodeSchema,
  CompiledMenuProjectionSchema,
  CompiledMenuNavigateBehaviorSchema,
  MenuAccessRequirementSchema,
  MenuActionBehaviorSchema,
  MenuActionRegistrationSchema,
  MenuBehaviorSchema,
  MenuBoundedInputSchema,
  MenuContributionProviderRegistrationSchema,
  MenuContributionResultSchema,
  MenuContributionSchema,
  MenuDefinitionSchema,
  MenuDefinitionSetSchema,
  MenuDividerNodeSchema,
  MenuGroupNodeSchema,
  MenuItemNodeSchema,
  MenuNavigateBehaviorSchema,
  MenuNavigationTargetSchema,
  MenuNodeSchema,
  MenuPageRefSchema,
  MenuPageRegistrationSchema,
  MenuRuntimeBundleSchema,
  MenuRuntimeInputBindingSchema,
  MenuSourceInputBindingSchema,
} from '../contracts/menu';
export {
  PageDefinitionSchema,
  PageGuardProjectionSchema,
  PageNavigationProjectionSchema,
  PageRendererProjectionSchema,
  PageRouteProjectionSchema,
  PageRuntimeDescriptorSchema,
  PageRuntimeProjectionSchema,
  PageTypeSchema,
  PageVisibilitySchema,
} from '../contracts/page';
export {
  ApplicationHandoffEndpointSchema,
  ApplicationHandoffSchema,
  OverlayNodeSchema,
  OverlayZIndexLaneSchema,
  ProductContextSchema,
  RenderActivationSchema,
  RenderLifecycleSchema,
  RenderLayoutSchema,
  RenderNodeKindSchema,
  RenderNodeSchema,
  RenderNodeStateSchema,
  RenderResponsiveRuleSchema,
  RenderScrollSchema,
  RenderSurfaceSchema,
  RenderTreeSchema,
  ViewProviderDescriptorSchema,
} from '../contracts/render';
export {
  ChangeImpactGraphSchema,
  ConceptDefinitionSchema,
  DomainCommandDefinitionSchema,
  DomainCommandSchema,
  ProductDeclarationSchema,
} from '../contracts/semantic';
export {
  CurrentUserMenuActionItemSchema,
  CurrentUserMenuConfigSchema,
  CurrentUserMenuControlItemSchema,
  CurrentUserMenuDisplayTextSchema,
  CurrentUserMenuItemSchema,
  CurrentUserMenuNavigationItemSchema,
  CurrentUserMenuProfileSchema,
  CurrentUserMenuSectionSchema,
  TenantApplicationConfigSchema,
  TenantListFooterConfigSchema,
  TenantLandingPageConfigSchema,
  TenantProductConfigSchema,
  TenantRuntimeConfigSchema,
  TenantTrendRadarCollectionTargetSchema,
  TenantTrendRadarSourceSchema,
  TenantTrendRadarSourcesSchema,
  TenantWorkbenchConfigSchema,
  TenantWorkbenchPageContextSchema,
  TenantWorkbenchPageEnvelopeSchema,
  TenantWorkbenchPageGroupSchema,
} from '../contracts/tenant';
export {
  ResolvedThemeTokensSchema,
  ThemeTokenGroupSchema,
  ThemeTokenTypeSchema,
  ThemeTokenSchema,
  ThemeTokensSchema,
} from '../contracts/theme';
export {
  BrandGeneticsProfileSchema,
  BrandBodySchema,
  HotwordBodySchema,
  ProductBodySchema,
  RadarActionRecordSchema,
  RadarAnalysisAssetSchema,
  RadarAnalysisDetailSchema,
  RadarAnalysisRunSchema,
  RadarDecisionMetricsSchema,
  RadarOpportunityMatrixSchema,
  RadarOpportunityMatrixPointSchema,
  RadarPanoramaEdgeSchema,
  RadarPanoramaNodeSchema,
  RadarPanoramaSchema,
  RadarQueryBodySchema,
  RadarScoreModelBodySchema,
  RadarScoreProjectionSchema,
  RadarSelectionSchema,
  RadarWritebackRecordSchema,
  SavedRadarQuerySchema,
  TrendRadarCollectionArtifactProjectionSchema,
  TrendRadarCollectionArtifactRefSchema,
  TrendRadarCollectionAssetRefSchema,
  TrendRadarCollectionDecisionAxisSchema,
  TrendRadarCollectionDecisionProjectionSchema,
  TrendRadarCollectionItemSchema,
  TrendRadarCollectionProjectionWritebackSchema,
  TrendRadarCollectionRecipeEntrySchema,
  TrendRadarCollectionRecipeSchema,
  TrendRadarCollectionRunRefSchema,
  TrendRadarCollectionSelectionRefSchema,
  TrendRadarCollectionSubjectRefSchema,
  TrendIngestRunSchema,
  TrendMetricSnapshotSchema,
  TrendSourceSchema,
  TrendSourceRecordSchema,
} from '../contracts/trend';
export {
  ConductorTaskDefinitionSchema,
  ConductorTaskTypeSchema,
  ConductorWorkflowDefinitionSchema,
  WorkflowDefinitionSchema,
  WorkflowEdgeSchema,
  WorkflowNodeSchema,
  WorkflowOutputBindingSchema,
  WorkflowParameterSchema,
  WorkflowParameterTypeSchema,
  WorkflowTriggerSchema,
  WorkflowValidationIssueSchema,
} from '../contracts/workflow-definition';
export {
  WorkflowCatalogEntrySchema,
  WorkflowCompletionCommitSchema,
  WorkflowCompletionReceiptSchema,
  WorkflowPublicationSchema,
} from '../contracts/workflow-runtime';

import { ArtifactManifestSchema, OutputRecordSchema } from '../contracts/artifact';
import {
  AgentSessionCommandResultSchema,
  AgentSessionCommandSchema,
  AgentSessionContinuationRequestSchema,
  AgentSessionContinuationResultSchema,
  AgentSessionEventSchema,
  AgentSessionRunEventSchema,
  AgentSessionRunSchema,
  AgentSessionTargetedCommandSchema,
  AgentSessionViewModelSchema,
  AgentWorkbenchComposerViewModelSchema,
  AgentWorkbenchNavigationViewModelSchema,
  AgentWorkbenchQuickStartViewModelSchema,
} from '../contracts/agent';
import { CapabilityManifestSchema, CapabilityRegistryDocumentSchema } from '../contracts/capability';
import {
  AgentRuntimeEventSchema,
  CompletionEventSchema,
  CompletionHeaderSchema,
  ExecutionLinkSchema,
  RequestScopeSchema,
} from '../contracts/context';
import {
  ApplicationRunSchema,
  BodyRelationRecordSchema,
  DataContinuityEnvelopeSchema,
  ExpiringAccessGrantSchema,
} from '../contracts/continuity';
import {
  DomainEventSchema,
  LineageRecordSchema,
  OntologyDefinitionSchema,
  ProjectionSpecSchema,
} from '../contracts/data';
import {
  MenuDefinitionSchema,
  MenuDefinitionSetSchema,
  MenuRuntimeBundleSchema,
} from '../contracts/menu';
import { PageDefinitionSchema, PageRuntimeDescriptorSchema, PageRuntimeProjectionSchema } from '../contracts/page';
import {
  ApplicationHandoffSchema,
  OverlayNodeSchema,
  RenderNodeSchema,
  RenderTreeSchema,
  ViewProviderDescriptorSchema,
} from '../contracts/render';
import { TenantProductConfigSchema, TenantRuntimeConfigSchema } from '../contracts/tenant';
import {
  ChangeImpactGraphSchema,
  ConceptDefinitionSchema,
  DomainCommandDefinitionSchema,
  DomainCommandSchema,
  ProductDeclarationSchema,
} from '../contracts/semantic';
import { ThemeTokensSchema } from '../contracts/theme';
import {
  BrandGeneticsProfileSchema,
  BrandBodySchema,
  HotwordBodySchema,
  ProductBodySchema,
  RadarActionRecordSchema,
  RadarAnalysisDetailSchema,
  RadarAnalysisRunSchema,
  RadarOpportunityMatrixSchema,
  RadarPanoramaSchema,
  RadarQueryBodySchema,
  RadarScoreModelBodySchema,
  RadarScoreProjectionSchema,
  RadarSelectionSchema,
  RadarWritebackRecordSchema,
  SavedRadarQuerySchema,
  TrendRadarCollectionItemSchema,
  TrendIngestRunSchema,
  TrendMetricSnapshotSchema,
  TrendSourceRecordSchema,
} from '../contracts/trend';
import { ConductorWorkflowDefinitionSchema, WorkflowDefinitionSchema } from '../contracts/workflow-definition';
import {
  WorkflowCatalogEntrySchema,
  WorkflowCompletionCommitSchema,
  WorkflowCompletionReceiptSchema,
  WorkflowPublicationSchema,
} from '../contracts/workflow-runtime';

export const canonicalContractSchemas = {
  'agent-session-command': AgentSessionCommandSchema,
  'agent-session-targeted-command': AgentSessionTargetedCommandSchema,
  'agent-session-command-result': AgentSessionCommandResultSchema,
  'agent-session-continuation-request': AgentSessionContinuationRequestSchema,
  'agent-session-continuation-result': AgentSessionContinuationResultSchema,
  'agent-session-event': AgentSessionEventSchema,
  'agent-session-run-event': AgentSessionRunEventSchema,
  'agent-session-run': AgentSessionRunSchema,
  'agent-session-view-model': AgentSessionViewModelSchema,
  'agent-workbench-composer-view-model': AgentWorkbenchComposerViewModelSchema,
  'agent-workbench-navigation-view-model': AgentWorkbenchNavigationViewModelSchema,
  'agent-workbench-quick-start-view-model': AgentWorkbenchQuickStartViewModelSchema,
  'agent-runtime-event': AgentRuntimeEventSchema,
  'application-run': ApplicationRunSchema,
  'application-handoff': ApplicationHandoffSchema,
  'artifact-manifest': ArtifactManifestSchema,
  'brand-body': BrandBodySchema,
  'body-relation-record': BodyRelationRecordSchema,
  'brand-genetics-profile': BrandGeneticsProfileSchema,
  'capability-manifest': CapabilityManifestSchema,
  'capability-registry': CapabilityRegistryDocumentSchema,
  'change-impact-graph': ChangeImpactGraphSchema,
  'concept-definition': ConceptDefinitionSchema,
  'completion-event': CompletionEventSchema,
  'completion-header': CompletionHeaderSchema,
  'conductor-workflow-definition': ConductorWorkflowDefinitionSchema,
  'domain-event': DomainEventSchema,
  'domain-command': DomainCommandSchema,
  'domain-command-definition': DomainCommandDefinitionSchema,
  'data-continuity-envelope': DataContinuityEnvelopeSchema,
  'execution-link': ExecutionLinkSchema,
  'expiring-access-grant': ExpiringAccessGrantSchema,
  'hotword-body': HotwordBodySchema,
  'lineage-record': LineageRecordSchema,
  'menu-definition': MenuDefinitionSchema,
  'menu-definition-set': MenuDefinitionSetSchema,
  'menu-runtime-bundle': MenuRuntimeBundleSchema,
  'ontology-definition': OntologyDefinitionSchema,
  'overlay-node': OverlayNodeSchema,
  'output-record': OutputRecordSchema,
  'page-definition': PageDefinitionSchema,
  'page-runtime-descriptor': PageRuntimeDescriptorSchema,
  'page-runtime-projection': PageRuntimeProjectionSchema,
  'projection-spec': ProjectionSpecSchema,
  'product-declaration': ProductDeclarationSchema,
  'product-body': ProductBodySchema,
  'radar-action-record': RadarActionRecordSchema,
  'radar-analysis-detail': RadarAnalysisDetailSchema,
  'radar-analysis-run': RadarAnalysisRunSchema,
  'radar-opportunity-matrix': RadarOpportunityMatrixSchema,
  'radar-panorama': RadarPanoramaSchema,
  'radar-query-body': RadarQueryBodySchema,
  'radar-score-model-body': RadarScoreModelBodySchema,
  'radar-score-projection': RadarScoreProjectionSchema,
  'radar-selection': RadarSelectionSchema,
  'radar-writeback-record': RadarWritebackRecordSchema,
  'request-scope': RequestScopeSchema,
  'render-node': RenderNodeSchema,
  'render-tree': RenderTreeSchema,
  'saved-radar-query': SavedRadarQuerySchema,
  'tenant-product-config': TenantProductConfigSchema,
  'tenant-runtime-config': TenantRuntimeConfigSchema,
  'theme-tokens': ThemeTokensSchema,
  'trend-radar-collection-item': TrendRadarCollectionItemSchema,
  'trend-ingest-run': TrendIngestRunSchema,
  'trend-metric-snapshot': TrendMetricSnapshotSchema,
  'trend-source-record': TrendSourceRecordSchema,
  'view-provider-descriptor': ViewProviderDescriptorSchema,
  'workflow-definition': WorkflowDefinitionSchema,
  'workflow-catalog-entry': WorkflowCatalogEntrySchema,
  'workflow-publication': WorkflowPublicationSchema,
  'workflow-completion-commit': WorkflowCompletionCommitSchema,
  'workflow-completion-receipt': WorkflowCompletionReceiptSchema,
} as const;

export type CanonicalContractSchemaName = keyof typeof canonicalContractSchemas;
